### ISSUE TITLE
延迟卡顿

### ISSUE THREAD

**Issue by pikawindy** [PandaQuQ/P3P_HD_CHINESE#2]
机型：小米k30s
问题：一开始是用你百度的包，在手机ppsspp上对话都卡顿很明显，设置渲染引擎，跳帧，渲染分辨率那些都调整过了，还是没变化。
然后我留意到你b站视频有提到你的美版高清素材包是6倍的，我就找了给三倍的试了下还是那样卡。
最后我才发现用【初见真身】的三倍包但不加你的高清中文包是不卡的，结论是你的高清中文包有问题？因为太高清了也是六倍？

**Comment by PandaQuQ** [comment]
pikawindy 你好：
手机没在考虑范围内,可以考虑尝试下pc端。
PandaQuQ



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月23日(周日) 上午10:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PandaQuQ/P3P_HD_CHINESE] 延迟卡顿 (Issue #2)




 
机型：小米k30s
 问题：一开始是用你百度的包，在手机ppsspp上对话都卡顿很明显，设置渲染引擎，跳帧，渲染分辨率那些都调整过了，还是没变化。
 然后我留意到你b站视频有提到你的美版高清素材包是6倍的，我就找了给三倍的试了下还是那样卡。
 最后我才发现用【初见真身】的三倍包但不加你的高清中文包是不卡的，结论是你的高清中文包有问题？因为太高清了也是六倍？
